export const WS_MSG_RECIEVED = 'WS_MSG_RECEIVED';
export const JOIN_ROOM = 'JOIN_ROOM';
export const CREATE_GAME_ROOM = 'CREATE_GAME_ROOM';
export const CREATE_GAME_ROOM_SUCCESS = 'CREATE_GAME_ROOM_SUCCESS';