export const WS_MSG_RECIEVED = 'WS_MSG_RECEIVED';

export const ENTER_GAME_ROOM = 'ENTER_GAME_ROOM';
export const ENTER_GAME_ROOM_SUCCESS = 'ENTER_GAME_ROOM_SUCCESS';

export const CREATE_GAME_ROOM = 'CREATE_GAME_ROOM';
export const CREATE_GAME_ROOM_SUCCESS = 'CREATE_GAME_ROOM_SUCCESS';

export const SOCKET_MESSAGE = 'SOCKET_MESSAGE';
export const ENTERED_ROOM = 'ENTERED_ROOM';
export const NEW_PLAYER_JOINED = 'NEW_PLAYER_JOINED';
export const PLAYER_READY = 'PLAYER_READY';

export const MESSAGE_TO_SERVER = 'MESSAGE_TO_SERVER';